events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        # Pastikan mengarah ke public
        root /var/www/html/public;
        index index.php index.html;

        # Memastikan file statis (CSS/JS) dicari dengan benar
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Konfigurasi PHP
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Tambahkan ini untuk menangani caching aset Vite
        location ~ ^/build/ {
            access_log off;
            expires max;
            add_header Cache-Control "public, must-revalidate, proxy-revalidate";
        }

        # Menghindari akses ke file .env atau .git
        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}